//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Plugin.BlueGreenConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwsWrapperDataProvider.Plugin.BlueGreenConnection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] currentPhase: {1}, exception while querying for blue/green status..
        /// </summary>
        internal static string BlueGreenStatusMonitor_CollectStatus_Exception {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_CollectStatus_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] No entries in status table..
        /// </summary>
        internal static string BlueGreenStatusMonitor_CollectStatus_NoEntriesInStatusTable {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_CollectStatus_NoEntriesInStatusTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] (status not available) currentPhase: {1}.
        /// </summary>
        internal static string BlueGreenStatusMonitor_CollectStatus_StatusNotAvailable {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_CollectStatus_StatusNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while retrieving the blue/green fast switchover metadata..
        /// </summary>
        internal static string BlueGreenStatusMonitor_CollectStatus_UnhandledException {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_CollectStatus_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unhandled SQLException..
        /// </summary>
        internal static string BlueGreenStatusMonitor_CollectStatus_UnhandledSqlException {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_CollectStatus_UnhandledSqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Creating a new HostListProvider, clusterId: {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_InitHostListProvider_CreateHostListProvider {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_InitHostListProvider_CreateHostListProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize HostListProvider since connection host information is null..
        /// </summary>
        internal static string BlueGreenStatusMonitor_InitHostListProvider_HostSpecNull {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_InitHostListProvider_HostSpecNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Opened monitoring connection to {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_OpenConnection_OpenedConnection {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_OpenConnection_OpenedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Opened monitoring connection (IP) to {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_OpenConnection_OpenedConnectionWithIp {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_OpenConnection_OpenedConnectionWithIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Opening monitoring connection to {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_OpenConnection_OpeningConnection {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_OpenConnection_OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Opening monitoring connection (IP) to {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_OpenConnection_OpeningConnectionWithIp {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_OpenConnection_OpeningConnectionWithIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Status changed to: {1}..
        /// </summary>
        internal static string BlueGreenStatusMonitor_RunMonitoringLoop_StatusChanged {
            get {
                return ResourceManager.GetString("BlueGreenStatusMonitor_RunMonitoringLoop_StatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;, role: {1}] {2}.
        /// </summary>
        internal static string BlueGreenStatusProvider_PrepareStatus_InterimStatus {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_PrepareStatus_InterimStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green node &apos;&apos;{0}&apos;&apos; has changed its name to &apos;&apos;{1}&apos;&apos;..
        /// </summary>
        internal static string BlueGreenStatusProvider_RegisterIamHost_GreenNodeChangedName {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_RegisterIamHost_GreenNodeChangedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting context..
        /// </summary>
        internal static string BlueGreenStatusProvider_ResetContext {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_ResetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green switchover has timed out..
        /// </summary>
        internal static string BlueGreenStatusProvider_SwitchoverTimeout {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_SwitchoverTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Unknown BG phase &apos;&apos;{1}&apos;&apos;..
        /// </summary>
        internal static string BlueGreenStatusProvider_UnknownPhase {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UnknownPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Blue/Green Deployments isn&apos;&apos;t supported by database dialect {1}..
        /// </summary>
        internal static string BlueGreenStatusProvider_UnsupportedDialect {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UnsupportedDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Blue DNS update completed..
        /// </summary>
        internal static string BlueGreenStatusProvider_UpdateDnsFlags_BlueDnsCompleted {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UpdateDnsFlags_BlueDnsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Green DNS removed..
        /// </summary>
        internal static string BlueGreenStatusProvider_UpdateDnsFlags_GreenDnsRemoved {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UpdateDnsFlags_GreenDnsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Green topology changed..
        /// </summary>
        internal static string BlueGreenStatusProvider_UpdateDnsFlags_GreenTopologyChanged {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UpdateDnsFlags_GreenTopologyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bgdId: &apos;&apos;{0}&apos;&apos;] Blue/Green deployment is in rollback mode..
        /// </summary>
        internal static string BlueGreenStatusProvider_UpdatePhase_Rollback {
            get {
                return ResourceManager.GetString("BlueGreenStatusProvider_UpdatePhase_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is in progress. New connection can&apos;&apos;t be opened..
        /// </summary>
        internal static string RejectConnectRouting_Apply_InProgressCantConnect {
            get {
                return ResourceManager.GetString("RejectConnectRouting_Apply_InProgressCantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is in progress. Can&apos;&apos;t establish connection to &apos;&apos;{0}&apos;&apos;..
        /// </summary>
        internal static string SubstituteConnectRouting_Apply_InProgressCantOpenConnection {
            get {
                return ResourceManager.GetString("SubstituteConnectRouting_Apply_InProgressCantOpenConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting with IP address when IAM authentication is enabled requires an &apos;&apos;iamHost&apos;&apos; parameter..
        /// </summary>
        internal static string SubstituteConnectRouting_Apply_RequireIamHost {
            get {
                return ResourceManager.GetString("SubstituteConnectRouting_Apply_RequireIamHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is in progress. The  &apos;&apos;connect&apos;&apos; call will be delayed until switchover is completed..
        /// </summary>
        internal static string SuspendConnectRouting_Apply_InProgressHoldConnect {
            get {
                return ResourceManager.GetString("SuspendConnectRouting_Apply_InProgressHoldConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is still in progress after {0} ms. Try to connect again later..
        /// </summary>
        internal static string SuspendConnectRouting_Apply_InProgressTryConnectLater {
            get {
                return ResourceManager.GetString("SuspendConnectRouting_Apply_InProgressTryConnectLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is completed. Continue with connect call. The call was held for {0} ms..
        /// </summary>
        internal static string SuspendConnectRouting_Apply_SwitchoverCompleteContinueWithConnect {
            get {
                return ResourceManager.GetString("SuspendConnectRouting_Apply_SwitchoverCompleteContinueWithConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Blue/Green Deployment switchover is in progress. Suspend &apos;{0}&apos; call until switchover is completed.&quot;
        ///.
        /// </summary>
        internal static string SuspendExecuteRouting_Apply_InProgressSuspendMethod {
            get {
                return ResourceManager.GetString("SuspendExecuteRouting_Apply_InProgressSuspendMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Blue/Green Deployment switchover is still in progress after {0} ms. Try &apos;{1}&apos; again later.&quot;
        ///.
        /// </summary>
        internal static string SuspendExecuteRouting_Apply_StillInProgressTryMethodLater {
            get {
                return ResourceManager.GetString("SuspendExecuteRouting_Apply_StillInProgressTryMethodLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Blue/Green Deployment switchover is completed. Continue with &apos;{0}&apos; call. The call was held for {1} ms.&quot;
        ///.
        /// </summary>
        internal static string SuspendExecuteRouting_Apply_SwitchoverCompletedContinueWithMethod {
            get {
                return ResourceManager.GetString("SuspendExecuteRouting_Apply_SwitchoverCompletedContinueWithMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment status is completed. Continue with &apos;&apos;connect&apos;&apos; call. The call was held for {0} ms..
        /// </summary>
        internal static string SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CompletedContinueWithConnect {
            get {
                return ResourceManager.GetString("SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CompletedContinueWithConne" +
                        "ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A corresponding node for &apos;&apos;{0}&apos;&apos; is found. Continue with connect call. The call was held for {1} ms..
        /// </summary>
        internal static string SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CorrespondingNodeFoundContinueWithConnect {
            get {
                return ResourceManager.GetString("SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CorrespondingNodeFoundCont" +
                        "inueWithConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is still in progress and a corresponding node for &apos;&apos;{0}&apos;&apos; is not found after {1} ms. Try to connect again later..
        /// </summary>
        internal static string SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CorrespondingNodeNotFoundTryConnectLater {
            get {
                return ResourceManager.GetString("SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_CorrespondingNodeNotFoundT" +
                        "ryConnectLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue/Green Deployment switchover is in progress and a corresponding node for &apos;&apos;{0}&apos;&apos; is not found. The &apos;&apos;connect&apos;&apos; call will be delayed..
        /// </summary>
        internal static string SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_WaitConnectUntilCorrespondingNodeFound {
            get {
                return ResourceManager.GetString("SuspendUntilCorrespondingNodeFoundConnectRouting_Apply_WaitConnectUntilCorrespond" +
                        "ingNodeFound", resourceCulture);
            }
        }
    }
}
