//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Plugin.KmsEncryption.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwsWrapperDataProvider.Plugin.KmsEncryption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value was produced when encrypting {0}..
        /// </summary>
        internal static string ColumnEncryptor_EncryptAsync_NoValueProduced {
            get {
                return ResourceManager.GetString("ColumnEncryptor_EncryptAsync_NoValueProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key material is recorded for {0}. The encryption metadata names key &apos;{1}&apos;, but that key was not found in the key storage table..
        /// </summary>
        internal static string ColumnEncryptor_Require_NoKeyMaterial {
            get {
                return ResourceManager.GetString("ColumnEncryptor_Require_NoKeyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} is NULL and cannot be read as {1}..
        /// </summary>
        internal static string DecryptingDataReader_Converted_ColumnIsNull {
            get {
                return ResourceManager.GetString("DecryptingDataReader_Converted_ColumnIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The columns of this result cannot be described by {0}, so the kmsEncryption plugin cannot tell which of them are encrypted. Values would be returned as stored rather than decrypted. Use a driver whose reader implements IDbColumnSchemaGenerator or supports GetSchemaTable..
        /// </summary>
        internal static string DecryptingDataReader_DescribeColumns_CannotDescribe {
            get {
                return ResourceManager.GetString("DecryptingDataReader_DescribeColumns_CannotDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unwrap DecryptingDataReader to {0}..
        /// </summary>
        internal static string DecryptingDataReader_Unwrap_CannotUnwrap {
            get {
                return ResourceManager.GetString("DecryptingDataReader_Unwrap_CannotUnwrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property is required by the {1} plugin..
        /// </summary>
        internal static string EncryptionConfig_FromProperties_RegionRequired {
            get {
                return ResourceManager.GetString("EncryptionConfig_FromProperties_RegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must not be empty..
        /// </summary>
        internal static string EncryptionConfig_FromProperties_SchemaEmpty {
            get {
                return ResourceManager.GetString("EncryptionConfig_FromProperties_SchemaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must be a positive number..
        /// </summary>
        internal static string EncryptionConfig_PositiveNumber_Required {
            get {
                return ResourceManager.GetString("EncryptionConfig_PositiveNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value stored in {0} failed its integrity check. Either it is not encrypted (written without the kmsEncryption plugin, as a literal, or by another application), or a different key is configured for this column than the one it was encrypted with, or the stored bytes have been modified..
        /// </summary>
        internal static string EncryptionException_IntegrityCheckFailed {
            get {
                return ResourceManager.GetString("EncryptionException_IntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} length for {1}: expected {2} bytes but got {3}..
        /// </summary>
        internal static string EncryptionException_InvalidKeyLength {
            get {
                return ResourceManager.GetString("EncryptionException_InvalidKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored encrypted value is malformed: {0}..
        /// </summary>
        internal static string EncryptionException_Malformed {
            get {
                return ResourceManager.GetString("EncryptionException_Malformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value stored in {0} is not encrypted: it is {1} bytes, and an encrypted value is never shorter than {2}. It was most likely written without the kmsEncryption plugin enabled, written as a literal in the statement rather than as a parameter, or written by another application or tool..
        /// </summary>
        internal static string EncryptionException_NotEncrypted {
            get {
                return ResourceManager.GetString("EncryptionException_NotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported encryption algorithm &apos;{0}&apos;. Supported algorithms are &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string EncryptionException_UnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionException_UnsupportedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of type &apos;{0}&apos; cannot be encrypted. Supported types are string, int, long, double, float, bool, decimal, DateTime, DateOnly, TimeOnly, DateTimeOffset and byte[]..
        /// </summary>
        internal static string EncryptionException_UnsupportedType {
            get {
                return ResourceManager.GetString("EncryptionException_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decrypt a value..
        /// </summary>
        internal static string EncryptionService_Decrypt_Failed {
            get {
                return ResourceManager.GetString("EncryptionService_Decrypt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify the integrity tag of an encrypted value..
        /// </summary>
        internal static string EncryptionService_Decrypt_HmacFailed {
            get {
                return ResourceManager.GetString("EncryptionService_Decrypt_HmacFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored encrypted value could not be decrypted. The wrong key may be configured for this column..
        /// </summary>
        internal static string EncryptionService_Decrypt_WrongKey {
            get {
                return ResourceManager.GetString("EncryptionService_Decrypt_WrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to encrypt a value..
        /// </summary>
        internal static string EncryptionService_Encrypt_Failed {
            get {
                return ResourceManager.GetString("EncryptionService_Encrypt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute the integrity tag for an encrypted value..
        /// </summary>
        internal static string EncryptionService_Encrypt_HmacFailed {
            get {
                return ResourceManager.GetString("EncryptionService_Encrypt_HmacFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored data key for key &apos;{0}&apos; is not valid base64..
        /// </summary>
        internal static string KeyManager_DecryptDataKeyAsync_InvalidBase64 {
            get {
                return ResourceManager.GetString("KeyManager_DecryptDataKeyAsync_InvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS KMS could not decrypt the data key for key &apos;{0}&apos;. Check that the master key &apos;{1}&apos; exists and that this application is permitted to call kms:Decrypt on it..
        /// </summary>
        internal static string KeyManager_DecryptDataKeyAsync_KmsFailed {
            get {
                return ResourceManager.GetString("KeyManager_DecryptDataKeyAsync_KmsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data key for key &apos;{0}&apos; is {1} bytes but {2} requires {3}..
        /// </summary>
        internal static string KeyManager_DecryptDataKeyAsync_WrongLength {
            get {
                return ResourceManager.GetString("KeyManager_DecryptDataKeyAsync_WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported key specification &apos;{0}&apos;. Supported specifications are AES_256 and AES_128..
        /// </summary>
        internal static string KeyManager_KeySpecToAlgorithm_Unsupported {
            get {
                return ResourceManager.GetString("KeyManager_KeySpecToAlgorithm_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kmsEncryption plugin was used before Initialise was called..
        /// </summary>
        internal static string KmsEncryptionPlugin_Initialise_NotInitialised {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_Initialise_NotInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kmsEncryption plugin cannot decrypt the result of ExecuteScalar because no reader is returned. Use ExecuteReader for statements that select an encrypted column..
        /// </summary>
        internal static string KmsEncryptionPlugin_WarnIfUnsupported_ScalarNotDecryptable {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_WarnIfUnsupported_ScalarNotDecryptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kmsEncryption plugin cannot read its metadata because no host is connected yet..
        /// </summary>
        internal static string MetadataManager_CacheKey_NoHostConnected {
            get {
                return ResourceManager.GetString("MetadataManager_CacheKey_NoHostConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kmsEncryption plugin could not read its metadata from schema &apos;{0}&apos;. Check that &apos;{0}.encryption_metadata&apos; and &apos;{0}.key_storage&apos; exist and are readable by this connection..
        /// </summary>
        internal static string MetadataManager_LoadAsync_MetadataUnreadable {
            get {
                return ResourceManager.GetString("MetadataManager_LoadAsync_MetadataUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must be a plain identifier containing only letters, digits, and underscores, and must not begin with a digit. It was &apos;{1}&apos;..
        /// </summary>
        internal static string MetadataManager_ValidateSchemaName_NotAnIdentifier {
            get {
                return ResourceManager.GetString("MetadataManager_ValidateSchemaName_NotAnIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this statement could not be read ({0}).
        /// </summary>
        internal static string SqlWriteScanner_Scan_Unreadable {
            get {
                return ResourceManager.GetString("SqlWriteScanner_Scan_Unreadable", resourceCulture);
            }
        }

        internal static string KeyManager_DecryptDataKeyAsync_RequestingDecrypt {
            get {
                return ResourceManager.GetString("KeyManager_DecryptDataKeyAsync_RequestingDecrypt", resourceCulture);
            }
        }

        internal static string KmsEncryptionPlugin_WarnIfScalarIsCiphertext_ScalarLooksEncrypted {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_WarnIfScalarIsCiphertext_ScalarLooksEncrypted", resourceCulture);
            }
        }

        internal static string KmsEncryptionPlugin_WarnIfUnsupported_RunningUnchanged {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_WarnIfUnsupported_RunningUnchanged", resourceCulture);
            }
        }

        internal static string KmsEncryptionPlugin_WarnIfUnsupported_UnnamedParameter {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_WarnIfUnsupported_UnnamedParameter", resourceCulture);
            }
        }

        internal static string KmsEncryptionPlugin_ExecuteBatchAsync_CannotCreateParameter {
            get {
                return ResourceManager.GetString("KmsEncryptionPlugin_ExecuteBatchAsync_CannotCreateParameter", resourceCulture);
            }
        }

        internal static string MetadataManager_RefreshAsync_Refreshed {
            get {
                return ResourceManager.GetString("MetadataManager_RefreshAsync_Refreshed", resourceCulture);
            }
        }

        internal static string MetadataManager_ClearCache_Cleared {
            get {
                return ResourceManager.GetString("MetadataManager_ClearCache_Cleared", resourceCulture);
            }
        }

        internal static string MetadataManager_ResolveTableOidsAsync_NoCatalogue {
            get {
                return ResourceManager.GetString("MetadataManager_ResolveTableOidsAsync_NoCatalogue", resourceCulture);
            }
        }

        internal static string MetadataManager_ResolveTableOidsAsync_MappingFailed {
            get {
                return ResourceManager.GetString("MetadataManager_ResolveTableOidsAsync_MappingFailed", resourceCulture);
            }
        }

        internal static string MetadataManager_ReadAsync_Loaded {
            get {
                return ResourceManager.GetString("MetadataManager_ReadAsync_Loaded", resourceCulture);
            }
        }
    }
}
