//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AwsWrapperDataProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_InvalidOperation {
            get {
                return ResourceManager.GetString("Error_InvalidOperation", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("Error_ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        internal static string Error_NotAwsWrapperConnection {
            get {
                return ResourceManager.GetString("Error_NotAwsWrapperConnection", resourceCulture);
            }
        }
        
        internal static string Error_NotImplementedDbCommand {
            get {
                return ResourceManager.GetString("Error_NotImplementedDbCommand", resourceCulture);
            }
        }
        
        internal static string Error_CantLoadTargetConnectionType {
            get {
                return ResourceManager.GetString("Error_CantLoadTargetConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_ProcessingAdoNetCall {
            get {
                return ResourceManager.GetString("Error_ProcessingAdoNetCall", resourceCulture);
            }
        }
        
        internal static string Error_UnknownPluginCode {
            get {
                return ResourceManager.GetString("Error_UnknownPluginCode", resourceCulture);
            }
        }
        
        internal static string Error_UnableToLoadPlugin {
            get {
                return ResourceManager.GetString("Error_UnableToLoadPlugin", resourceCulture);
            }
        }
        
        internal static string Error_UnableToCreateConnection {
            get {
                return ResourceManager.GetString("Error_UnableToCreateConnection", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("Error_ConnectionStringInvalid", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringHostListProviderNoSupport {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProviderNoSupport", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionUrlMissing {
            get {
                return ResourceManager.GetString("Error_ConnectionUrlMissing", resourceCulture);
            }
        }
        
        internal static string Error_HostCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_HostCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateCustomDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateCustomDialectType", resourceCulture);
            }
        }
        
        internal static string Error_NoDialectFoundForConnectionType {
            get {
                return ResourceManager.GetString("Error_NoDialectFoundForConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateDialectType", resourceCulture);
            }
        }
        
        internal static string Error_InvalidDialectType {
            get {
                return ResourceManager.GetString("Error_InvalidDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated monitoring..
        /// </summary>
        internal static string EfmHostMonitor_ActivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ActivatedMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while monitoring active contexts for host {0}: {1}, stack trace: {2}..
        /// </summary>
        internal static string EfmHostMonitor_ActiveContextsException {
            get {
                return ResourceManager.GetString("Error_UnableToFindValidDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated monitoring..
        /// </summary>
        internal static string EfmHostMonitor_DeactivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_DeactivatedMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception when identifying connection: {0}..
        /// </summary>
        internal static string EfmHostMonitor_ErrorIdentifyingConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ErrorIdentifyingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while aborting connection: {0}..
        /// </summary>
        internal static string EfmHostMonitor_ExceptionAbortingConnection {
            get {
                return ResourceManager.GetString("Error_TargetConnectionTypeNotFound", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StartMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartMonitoringThread", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StopMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StopMonitoringThread", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ExceptionDuringMonitoringStop {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ExceptionDuringMonitoringStop", resourceCulture);
            }
        }
        

        internal static string ClusterTopologyMonitor_InvalidQuery {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidQuery", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorGettingNetworkTimeout {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorGettingNetworkTimeout", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_InvalidTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidTopology", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_TopologyNotUpdated {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TopologyNotUpdated", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_IgnoringTopologyRequest {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.IgnoringTopologyRequest", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_TimeoutSetToZero {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TimeoutSetToZero", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_Interrupted {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.Interrupted", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StartingNodeMonitoringThreads {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartingNodeMonitoringThreads", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_WriterPickedUpFromNodeMonitors {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterPickedUpFromNodeMonitors", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_WriterMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorFetchingTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorFetchingTopology", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorProcessingQueryResults {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorProcessingQueryResults", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_UnexpectedTopologyQueryColumnCount {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.UnexpectedTopologyQueryColumnCount", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_DetectedWriter {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_DetectedWriter", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_ThreadCompleted {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_ThreadCompleted", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_WriterNodeChanged {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_WriterNodeChanged", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartMonitoringWhenStopped {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartMonitoringWhenStopped", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoring", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedPollingNewContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_NewContextsException {
            get {
                return ResourceManager.GetString("EfmHostMonitor_NewContextsException", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedPollingNewContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_OpeningMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpeningMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostDead {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostDead", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostNotResponding {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostNotResponding", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostAlive {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostAlive", resourceCulture);
            }
        }

        internal static string PluginService_ErrorClosingOldConnection {
            get {
                return ResourceManager.GetString("PluginService.ErrorClosingOldConnection", resourceCulture);
            }
        }
    }
}
