//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AwsWrapperDataProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_InvalidOperation {
            get {
                return ResourceManager.GetString("Error_InvalidOperation", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("Error_ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        internal static string Error_NotAwsWrapperConnection {
            get {
                return ResourceManager.GetString("Error_NotAwsWrapperConnection", resourceCulture);
            }
        }
        
        internal static string Error_NotImplementedDbCommand {
            get {
                return ResourceManager.GetString("Error_NotImplementedDbCommand", resourceCulture);
            }
        }
        
        internal static string Error_CantLoadTargetConnectionType {
            get {
                return ResourceManager.GetString("Error_CantLoadTargetConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_ProcessingAdoNetCall {
            get {
                return ResourceManager.GetString("Error_ProcessingAdoNetCall", resourceCulture);
            }
        }
        
        internal static string Error_UnknownPluginCode {
            get {
                return ResourceManager.GetString("Error_UnknownPluginCode", resourceCulture);
            }
        }
        
        internal static string Error_UnableToLoadPlugin {
            get {
                return ResourceManager.GetString("Error_UnableToLoadPlugin", resourceCulture);
            }
        }
        
        internal static string Error_UnableToCreateConnection {
            get {
                return ResourceManager.GetString("Error_UnableToCreateConnection", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("Error_ConnectionStringInvalid", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringHostListProviderNoSupport {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProviderNoSupport", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionUrlMissing {
            get {
                return ResourceManager.GetString("Error_ConnectionUrlMissing", resourceCulture);
            }
        }
        
        internal static string Error_HostCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_HostCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateCustomDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateCustomDialectType", resourceCulture);
            }
        }
        
        internal static string Error_NoDialectFoundForConnectionType {
            get {
                return ResourceManager.GetString("Error_NoDialectFoundForConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateDialectType", resourceCulture);
            }
        }
        
        internal static string Error_InvalidDialectType {
            get {
                return ResourceManager.GetString("Error_InvalidDialectType", resourceCulture);
            }
        }
        
        internal static string Error_UnableToFindValidDialectType {
            get {
                return ResourceManager.GetString("Error_UnableToFindValidDialectType", resourceCulture);
            }
        }
        
        internal static string Error_TargetConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("Error_TargetConnectionTypeNotFound", resourceCulture);
            }
        }
    }
}
