//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwsWrapperDataProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while querying for topology: {0}.
        /// </summary>
        internal static string ClusterTopologyMonitor_ErrorFetchingTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorFetchingTopology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the connection network timeout: {0}.
        /// </summary>
        internal static string ClusterTopologyMonitor_ErrorGettingNetworkTimeout {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorGettingNetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the results from the topology query: {0}.
        /// </summary>
        internal static string ClusterTopologyMonitor_ErrorProcessingQueryResults {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorProcessingQueryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping cluster topology monitoring after unhandled exception was thrown in monitoring thread for node {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_ExceptionDuringMonitoringStop {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ExceptionDuringMonitoringStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A topology refresh was requested, but the topology was already updated recently. Returning cached hosts:.
        /// </summary>
        internal static string ClusterTopologyMonitor_IgnoringTopologyRequest {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.IgnoringTopologyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread was interrupted while waiting for updated topology..
        /// </summary>
        internal static string ClusterTopologyMonitor_Interrupted {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.Interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to obtain the topology because the topology query was invalid. Please ensure you are connecting to an Aurora or RDS Db cluster..
        /// </summary>
        internal static string ClusterTopologyMonitor_InvalidQuery {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topology query returned an invalid topology - no writer instance detected..
        /// </summary>
        internal static string ClusterTopologyMonitor_InvalidTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidTopology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened monitoring connection to node {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting node monitoring threads..
        /// </summary>
        internal static string ClusterTopologyMonitor_StartingNodeMonitoringThreads {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartingNodeMonitoringThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cluster topology monitoring thread for {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_StartMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartMonitoringThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop cluster topology monitoring thread for {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_StopMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StopMonitoringThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A topology refresh was requested, but the given timeout for the request was 0ms. Returning cached hosts:.
        /// </summary>
        internal static string ClusterTopologyMonitor_TimeoutSetToZero {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TimeoutSetToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology hasn&apos;t been updated after {0} ms..
        /// </summary>
        internal static string ClusterTopologyMonitor_TopologyNotUpdated {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TopologyNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topology query returned a result with 0 columns. This may occur if the topology query is executed when the server is failing over..
        /// </summary>
        internal static string ClusterTopologyMonitor_UnexpectedTopologyQueryColumnCount {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.UnexpectedTopologyQueryColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monitoring connection is connected to a writer: {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_WriterMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterMonitoringConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer host detected by the node monitors was picked up by the topology monitor: {0}..
        /// </summary>
        internal static string ClusterTopologyMonitor_WriterPickedUpFromNodeMonitors {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterPickedUpFromNodeMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated monitoring..
        /// </summary>
        internal static string EfmHostMonitor_ActivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ActivatedMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while monitoring active contexts for host {0}: {1}, stack trace: {2}..
        /// </summary>
        internal static string EfmHostMonitor_ActiveContextsException {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ActiveContextsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated monitoring..
        /// </summary>
        internal static string EfmHostMonitor_DeactivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_DeactivatedMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception when identifying connection: {0}..
        /// </summary>
        internal static string EfmHostMonitor_ErrorIdentifyingConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ErrorIdentifyingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while aborting connection: {0}..
        /// </summary>
        internal static string EfmHostMonitor_ExceptionAbortingConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ExceptionAbortingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is alive: {0}..
        /// </summary>
        internal static string EfmHostMonitor_HostAlive {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is dead: {0}..
        /// </summary>
        internal static string EfmHostMonitor_HostDead {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is not responding: {0}, failure count: {1}..
        /// </summary>
        internal static string EfmHostMonitor_HostNotResponding {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while polling new contexts for host {0}: {1}, stack trace: {2}..
        /// </summary>
        internal static string EfmHostMonitor_NewContextsException {
            get {
                return ResourceManager.GetString("EfmHostMonitor_NewContextsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened a monitoring connection for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening a monitoring connection for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_OpeningMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpeningMonitoringConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started thread to monitor active contexts for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_StartedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started thread to poll new contexts for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_StartedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedPollingNewContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting monitoring for a monitor that has stopped..
        /// </summary>
        internal static string EfmHostMonitor_StartMonitoringWhenStopped {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartMonitoringWhenStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped monitoring threads for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_StoppedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped thread to monitor active contexts for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_StoppedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped thread to poll new contexts for host {0}..
        /// </summary>
        internal static string EfmHostMonitor_StoppedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedPollingNewContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load target connection type {0}.
        /// </summary>
        internal static string Error_CantLoadTargetConnectionType {
            get {
                return ResourceManager.GetString("Error_CantLoadTargetConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is already open..
        /// </summary>
        internal static string Error_ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("Error_ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionStringHostListProvider does not support {0}..
        /// </summary>
        internal static string Error_ConnectionStringHostListProviderNoSupport {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProviderNoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is invalid..
        /// </summary>
        internal static string Error_ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("Error_ConnectionStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection url is missing..
        /// </summary>
        internal static string Error_ConnectionUrlMissing {
            get {
                return ResourceManager.GetString("Error_ConnectionUrlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate custom dialect type &apos;{0}&apos;.
        /// </summary>
        internal static string Error_FailedToInstantiateCustomDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateCustomDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate dialect type {0}.
        /// </summary>
        internal static string Error_FailedToInstantiateDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host cannot be null or empty.
        /// </summary>
        internal static string Error_HostCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_HostCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dialect type provided..
        /// </summary>
        internal static string Error_InvalidDialectType {
            get {
                return ResourceManager.GetString("Error_InvalidDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        internal static string Error_InvalidOperation {
            get {
                return ResourceManager.GetString("Error_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dialect found for connection type {0}.
        /// </summary>
        internal static string Error_NoDialectFoundForConnectionType {
            get {
                return ResourceManager.GetString("Error_NoDialectFoundForConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided connection is not of type AwsWrapperConnection..
        /// </summary>
        internal static string Error_NotAwsWrapperConnection {
            get {
                return ResourceManager.GetString("Error_NotAwsWrapperConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided type doesn&apos;t implement IDbCommand..
        /// </summary>
        internal static string Error_NotImplementedDbCommand {
            get {
                return ResourceManager.GetString("Error_NotImplementedDbCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing this ADO.NET call..
        /// </summary>
        internal static string Error_ProcessingAdoNetCall {
            get {
                return ResourceManager.GetString("Error_ProcessingAdoNetCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target connection type not found..
        /// </summary>
        internal static string Error_TargetConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("Error_TargetConnectionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create connection..
        /// </summary>
        internal static string Error_UnableToCreateConnection {
            get {
                return ResourceManager.GetString("Error_UnableToCreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find valid dialect type for connection..
        /// </summary>
        internal static string Error_UnableToFindValidDialectType {
            get {
                return ResourceManager.GetString("Error_UnableToFindValidDialectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load plugin: {0}.
        /// </summary>
        internal static string Error_UnableToLoadPlugin {
            get {
                return ResourceManager.GetString("Error_UnableToLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown plugin code: {0}.
        /// </summary>
        internal static string Error_UnknownPluginCode {
            get {
                return ResourceManager.GetString("Error_UnknownPluginCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer detected by node monitoring thread: {0}..
        /// </summary>
        internal static string NodeMonitoringTask_DetectedWriter {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_DetectedWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node monitoring thread completed in {0} ms..
        /// </summary>
        internal static string NodeMonitoringTask_ThreadCompleted {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_ThreadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer node changed from {0} to node {1}..
        /// </summary>
        internal static string NodeMonitoringTask_WriterNodeChanged {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_WriterNodeChanged", resourceCulture);
            }
        }
    }
}
